package com.example.uni_kviz.ui.uni_kviz

import android.util.Log
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.uni_kviz.Graph
import com.example.uni_kviz.data.Fakultet
import com.example.uni_kviz.data.ImplementacijaBaze
import com.example.uni_kviz.data.Pitanje
import com.example.uni_kviz.data.PitanjeFakultet
import com.example.uni_kviz.data.PitanjeFakultetSpojeno
import kotlinx.coroutines.flow.collectLatest
import kotlinx.coroutines.launch

class UniKvizViewModel(
    private val implementacijaBaze: ImplementacijaBaze = Graph.implementacijaBaze
) : ViewModel() {
    var stanje by mutableStateOf(KvizState())
        private set

    init{
        getPitanjeFakultet()
        getPitanja()
        getFakulteti()

    }

    private fun getPitanjeFakultet(){
        viewModelScope.launch(){
            implementacijaBaze.pitanjeFakultet.collectLatest {
                stanje = stanje.copy(
                    pitanjaFakulteti = it
                )
            }
        }
    }

    private fun getPitanja(){
        viewModelScope.launch() {
            implementacijaBaze.pitanja.collectLatest {
                stanje = stanje.copy(
                    pitanja = it
                )

            }
        }
    }

    private fun getFakulteti(){
        viewModelScope.launch(){
            implementacijaBaze.fakulteti.collectLatest {
                stanje = stanje.copy(
                    fakulteti = it
                )
            }
        }
    }

    suspend fun dodajPitanja(){
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Da li ste više zainteresirani za prirodne nego za društvene znanosti?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Da li Vam je radi s brojevima i matematikom draži od rada s jezikom i književnošću?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Imate li interesa za medicinu i zdravstvo?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Da li ste kreativni i zanima vas umjetnost?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Volite li raditi s računarima i tehnologijom?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Da li imate interes za politiku i javne poslove?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Jeste li zainteresirani za proučavanje historije i kulture?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Preferirate li raditi s materijalima i izrađivati fizičke objekte?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Zanima li vas istraživanje prirodnih resursa i okoliša?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Da li vam se sviđa proučavanje ljudskog ponašanja i uma?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Volite li proučavati jezike i kulturu drugih zemalja?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Imate li interes za ekonomiju i poslovanje?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Da li vam se dopada proučavanje prava i pravnih sustava?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Preferirate li rad u industriji i tehničkim područjima?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Jeste li zainteresirani za arhitekturu i urbanizam?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Volite li raditi s medijima i novinarstvom?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Da li ste zainteresirani za obrazovanje i pedagogiju?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Preferirate li raditi u polju sporta i tjelesnog odgoja?"))
        implementacijaBaze.ubaciPitanje(Pitanje(pitanje="Imate li interes za proučavanje religije i duhovnosti?"))
    }

    suspend fun dodajFakultete(){
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Akademija likovnih umjetnosti"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Akademija scenskih umjetnosti"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Arhitektonski fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Centar za interdisciplinarne studije"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Ekonomski fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Elektrotehnički fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Fakultet islamskih nauka"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Fakultet politickih nauka"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Fakultet sporta i tjelesnog odgoja"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Fakultet za kriminalistiku, kriminologiju i sigurnosne studije"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Fakultet za saobraćaj i komunikacije"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Fakultet za upravu"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Fakultet zdravstvenih studija"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Farmaceutski fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Filozofski fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Gradevinski fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Katolicki bogoslovni fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Masinski fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Medicinski fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Muzicka akademija"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Pedagoski fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Poljoprivredno-prehrambeni fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Pravni fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Prirodno-matematicki fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Stomatoloski fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Sumarski fakultet"))
        implementacijaBaze.ubaciFakultet(Fakultet(ime="Veterinarski fakultet"))


    }

    suspend fun ubacivanjeBodova(){
        //Akademija likovnih umjetnosti

        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=1, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=1, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=1, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=1, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=1, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=1, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=1, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=1, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=1, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=1, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=1, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=1, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=1, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=1, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=1, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=1, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=1, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=1, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=1, bodovi=0))


//Akademija scenskih umjetnosti

        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=2, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=2, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=2, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=2, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=2, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=2, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=2, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=2, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=2, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=2, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=2, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=2, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=2, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=2, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=2, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=2, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=2, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=2, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=2, bodovi=2))
//Arhitektonski fakultet

        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=3, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=3, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=3, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=3, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=3, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=3, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=3, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=3, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=3, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=3, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=3, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=3, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=3, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=3, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=3, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=3, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=3, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=3, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=3, bodovi=0))//CIS

        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=4, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=4, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=4, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=4, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=4, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=4, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=4, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=4, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=4, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=4, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=4, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=4, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=4, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=4, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=4, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=4, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=4, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=4, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=4, bodovi=1))
//Ekonomski fakultet

        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=5, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=5, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=5, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=5, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=5, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=5, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=5, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=5, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=5, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=5, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=5, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=5, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=5, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=5, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=5, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=5, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=5, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=5, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=5, bodovi=0))
//Elektrotehnicki fakultet

        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=6, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=6, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=6, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=6, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=6, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=6, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=6, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=6, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=6, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=6, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=6, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=6, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=6, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=6, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=6, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=6, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=6, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=6, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=6, bodovi=0))
//Fakultet islamskih nauka
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=7, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=7, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=7, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=7, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=7, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=7, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=7, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=7, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=7, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=7, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=7, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=7, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=7, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=7, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=7, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=7, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=7, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=7, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=7, bodovi=10))
//Fakultet politickih nauka
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=8, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=8, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=8, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=8, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=8, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=8, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=8, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=8, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=8, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=8, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=8, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=8, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=8, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=8, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=8, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=8, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=8, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=8, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=8, bodovi=0))
//Fakultet sporta i tjelesnog odgoja
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=9, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=9, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=9, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=9, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=9, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=9, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=9, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=9, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=9, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=9, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=9, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=9, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=9, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=9, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=9, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=9, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=9, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=9, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=9, bodovi=0))

//10
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=10, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=10, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=10, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=10, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=10, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=10, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=10, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=10, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=10, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=10, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=10, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=10, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=10, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=10, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=10, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=10, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=10, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=10, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=10, bodovi=0))
//11
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=11, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=11, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=11, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=11, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=11, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=11, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=11, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=11, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=11, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=11, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=11, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=11, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=11, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=11, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=11, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=11, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=11, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=11, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=11, bodovi=0))
//12
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=12, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=12, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=12, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=12, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=12, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=12, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=12, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=12, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=12, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=12, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=12, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=12, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=12, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=12, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=12, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=12, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=12, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=12, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=12, bodovi=0))
//13
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=13, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=13, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=13, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=13, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=13, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=13, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=13, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=13, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=13, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=13, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=13, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=13, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=13, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=13, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=13, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=13, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=13, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=13, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=13, bodovi=0))
//14
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=14, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=14, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=14, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=14, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=14, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=14, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=14, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=14, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=14, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=14, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=14, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=14, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=14, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=14, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=14, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=14, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=14, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=14, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=14, bodovi=0))
//15
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=15, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=15, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=15, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=15, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=15, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=15, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=15, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=15, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=15, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=15, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=15, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=15, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=15, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=15, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=15, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=15, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=15, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=15, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=15, bodovi=4))
//16
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=16, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=16, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=16, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=16, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=16, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=16, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=16, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=16, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=16, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=16, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=16, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=16, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=16, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=16, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=16, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=16, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=16, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=16, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=16, bodovi=0))
//17
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=17, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=17, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=17, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=17, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=17, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=17, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=17, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=17, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=17, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=17, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=17, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=17, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=17, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=17, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=17, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=17, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=17, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=17, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=17, bodovi=10))
//19
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=19, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=19, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=19, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=19, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=19, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=19, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=19, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=19, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=19, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=19, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=19, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=19, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=19, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=19, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=19, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=19, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=19, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=19, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=19, bodovi=0))
//18
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=18, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=18, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=18, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=18, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=18, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=18, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=18, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=18, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=18, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=18, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=18, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=18, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=18, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=18, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=18, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=18, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=18, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=18, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=18, bodovi=0))

//katolicki

        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=20, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=20, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=20, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=20, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=20, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=20, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=20, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=20, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=20, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=20, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=20, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=20, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=20, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=20, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=20, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=20, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=20, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=20, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=20, bodovi=1))

// veterinarski

        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=27, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=27, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=27, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=27, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=27, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=27, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=27, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=27, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=27, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=27, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=27, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=27, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=27, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=27, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=27, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=27, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=27, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=27, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=27, bodovi=0))

// stomatoloski

        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=26, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=26, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=26, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=26, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=26, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=26, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=26, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=26, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=26, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=26, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=26, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=26, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=26, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=26, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=26, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=26, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=26, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=26, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=26, bodovi=0))

// poljoprivredni

        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=25, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=25, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=25, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=25, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=25, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=25, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=25, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=25, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=25, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=25, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=25, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=25, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=25, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=25, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=25, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=25, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=25, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=25, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=25, bodovi=0))

// pedagoski

        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=24, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=24, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=24, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=24, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=24, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=24, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=24, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=24, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=24, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=24, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=24, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=24, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=24, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=24, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=24, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=24, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=24, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=24, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=24, bodovi=0))

// muzicka

        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=23, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=23, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=23, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=23, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=23, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=23, bodovi=9))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=23, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=23, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=23, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=23, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=23, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=23, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=23, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=23, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=23, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=23, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=23, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=23, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=23, bodovi=1))

// medicina

        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=22, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=22, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=22, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=22, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=22, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=22, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=22, bodovi=7))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=22, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=22, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=22, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=22, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=22, bodovi=6))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=22, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=22, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=22, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=22, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=22, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=22, bodovi=8))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=22, bodovi=0))

// masinstvo

        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=1, id_fakultet=21, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=2, id_fakultet=21, bodovi=0))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=3, id_fakultet=21, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=4, id_fakultet=21, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=5, id_fakultet=21, bodovi=1))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=6, id_fakultet=21, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=7, id_fakultet=21, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=8, id_fakultet=21, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=9, id_fakultet=21, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=10, id_fakultet=21, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=11, id_fakultet=21, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=12, id_fakultet=21, bodovi=3))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=13, id_fakultet=21, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=14, id_fakultet=21, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=15, id_fakultet=21, bodovi=2))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=16, id_fakultet=21, bodovi=5))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=17, id_fakultet=21, bodovi=10))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=18, id_fakultet=21, bodovi=4))
        implementacijaBaze.ubaciPitanjeFakultet(PitanjeFakultet(id_pitanja=19, id_fakultet=21, bodovi=4))
    }
}

data class KvizState(
    val pitanja: List<Pitanje> = emptyList(),
    val fakulteti: List<Fakultet> = emptyList(),
    val pitanjaFakulteti: List<PitanjeFakultetSpojeno> = emptyList()
)